'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import {Plane,Route,CarFront,UserRoundCheck,BusFront,Sparkles,ArrowLeftRight,MapPin,Calendar,Clock,Users,BriefcaseBusiness,Minus,Plus,Search} from 'lucide-react';import {locations,services as defaultServices} from '@/data/catalog';import {useBookingStore} from '@/store/bookingStore';import {ServiceType} from '@/types';
const icons={airport:Plane,point:Route,'self-drive':CarFront,chauffeur:UserRoundCheck,group:BusFront,events:Sparkles};
export function BookingPanel({defaultService,serviceOptions=defaultServices}:{defaultService?:ServiceType;serviceOptions?:{id:ServiceType;title:string}[]}){const router=useRouter();const{trip,setTrip}=useBookingStore();const[errors,setErrors]=useState<Record<string,string>>({});const[peopleOpen,setPeopleOpen]=useState(false);const service=defaultService||trip.service;const setService=(s:ServiceType)=>setTrip({service:s});
 const submit=()=>{const e:Record<string,string>={};if(!trip.pickup)e.pickup='Choose a pickup location';if(!trip.destination&&service!=='chauffeur')e.destination='Choose a destination';if(!trip.date)e.date='Choose a date';setErrors(e);if(!Object.keys(e).length)router.push('/search')};
 const quick=[['Taipei','TPE — Taoyuan International Airport'],['Taipei','Jiufen'],['Taichung','Sun Moon Lake'],['Kaohsiung','KHH — Kaohsiung International Airport']];
 return <section className="booking-panel" id="book"><div className="service-tabs">{serviceOptions.map(s=>{const I=icons[s.id];return <button key={s.id} className={service===s.id?'active':''} onClick={()=>setService(s.id)}><I/>{s.title}</button>})}</div><div className="booking-fields">
 <label className={errors.pickup?'invalid':''}><span><MapPin/> {service==='self-drive'?'Pickup branch':'Pickup'}</span><input list="locations" value={trip.pickup} onChange={e=>setTrip({pickup:e.target.value,service})} placeholder="Enter pickup location"/><small>{errors.pickup}</small></label>
 {service!=='chauffeur'&&<><button className="swap" title="Swap locations" onClick={()=>setTrip({pickup:trip.destination,destination:trip.pickup})}><ArrowLeftRight/></button><label className={errors.destination?'invalid':''}><span><MapPin/> {service==='self-drive'?'Return branch':'Destination'}</span><input list="locations" value={trip.destination} onChange={e=>setTrip({destination:e.target.value})} placeholder="Where are you going?"/><small>{errors.destination}</small></label></>}
 <label className={errors.date?'invalid':''}><span><Calendar/> {service==='self-drive'?'Pickup date':'Date'}</span><input type="date" value={trip.date} onChange={e=>setTrip({date:e.target.value})}/><small>{errors.date}</small></label><label><span><Clock/> Time</span><input type="time" value={trip.time} onChange={e=>setTrip({time:e.target.value})}/></label>
 <div className="people-wrap"><button className="people" onClick={()=>setPeopleOpen(!peopleOpen)}><span><Users/> Passengers & luggage</span><b>{trip.passengers} traveler{trip.passengers>1?'s':''} · {trip.luggage} bag{trip.luggage!==1?'s':''}</b></button>{peopleOpen&&<div className="counter-pop"><Counter label="Passengers" icon={<Users/>} value={trip.passengers} min={1} change={x=>setTrip({passengers:x})}/><Counter label="Luggage" icon={<BriefcaseBusiness/>} value={trip.luggage} min={0} change={x=>setTrip({luggage:x})}/><button className="done" onClick={()=>setPeopleOpen(false)}>Done</button></div>}</div>
 <button className="search-btn" onClick={submit}><Search/> Search vehicles <span>→</span></button></div><datalist id="locations">{locations.map(x=><option key={x.name}>{x.name}</option>)}</datalist>
 {service==='airport'&&<div className="conditional"><input aria-label="Flight number" placeholder="Flight number (e.g. BR156)" value={trip.flight||''} onChange={e=>setTrip({flight:e.target.value.toUpperCase()})}/>{trip.flight==='BR156'&&<span>✓ EVA Air · Terminal 2 · On time, 15:40</span>}</div>}
 {service==='chauffeur'&&<div className="conditional"><select aria-label="Duration"><option>2 hours</option><option>4 hours</option><option>8 hours</option><option>10 hours</option><option>Full day</option></select><span>Includes a professional bilingual driver.</span></div>}
 {service==='events'&&<div className="conditional"><select aria-label="Event type"><option>Wedding</option><option>Conference</option><option>VIP</option><option>Corporate Event</option><option>Concert</option><option>Exhibition</option></select><input type="number" min="1" defaultValue="2" aria-label="Number of vehicles"/></div>}
 <div className="quick"><b>Popular:</b>{quick.map(x=><button onClick={()=>setTrip({pickup:x[0],destination:x[1]})} key={x.join()}>{x[0]} → {x[1]}</button>)}</div></section>}
function Counter({label,icon,value,min,change}:{label:string;icon:React.ReactNode;value:number;min:number;change:(x:number)=>void}){return <div className="counter"><span>{icon}{label}</span><button onClick={()=>change(Math.max(min,value-1))}><Minus/></button><b>{value}</b><button onClick={()=>change(value+1)}><Plus/></button></div>}
