'use client';
import Link from 'next/link'; import {usePathname} from 'next/navigation'; import {useEffect,useRef,useState} from 'react';
import {Home,CalendarDays,Plane,Route,CarFront,UserRoundCheck,BusFront,Compass,Gift,HelpCircle,Menu,X,Heart,LogIn,Globe2,Search,Settings,MapPin} from 'lucide-react'; import {GlobalSearch} from './GlobalSearch';
const nav=[['Home','/',Home],['Book a Ride','/#book',CalendarDays],['Airport Transfer','/airport-transfer',Plane],['Point-to-Point','/point-to-point',Route],['Self-Drive Rental','/self-drive',CarFront],['Chauffeur','/chauffeur',UserRoundCheck],['Group Transport','/group-transport',BusFront],['Fleet','/fleet',CarFront],['Explore Taiwan','/explore',Compass],['Offers','/offers',Gift],['Help Center','/help',HelpCircle]] as const;
const drawerNav=[['Book a Ride','/#book',CalendarDays],['My Bookings','/account/bookings',CalendarDays],['Favorites','/account/favorites',Heart],['Fleet','/fleet',CarFront],['Explore Taiwan','/explore',MapPin],['Offers','/offers',Gift],['Help','/help',HelpCircle],['Settings','/account/profile',Settings]] as const;
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const[drawer,setDrawer]=useState(false);const[lang,setLang]=useState('EN');const closeRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==='Escape'&&setDrawer(false);window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 if(path.startsWith('/admin'))return <>{children}</>;
 return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand"><span className="brandmark"><i/><i/><i/></span><span>FLEET <b>OS</b><small>TAIWAN MOBILITY</small></span></Link><nav>{nav.map(([label,href,Icon])=><Link title={label} className={path===href?'active':''} href={href} key={label}><Icon size={19}/><span>{label}</span></Link>)}</nav><Link href="/explore" className="explore-card"><strong>Explore Taiwan</strong><span>One journey at a time</span><b>Start exploring →</b></Link></aside>
 <div className="main"><header><GlobalSearch/><div className="header-actions"><button onClick={()=>setLang(lang==='EN'?'繁中':'EN')}><Globe2/> {lang}</button><Link href="/login"><LogIn/> <span>Sign in</span></Link><button aria-label="Open menu" onClick={()=>setDrawer(true)}><Menu/></button></div></header>{children}<footer><div><b>FLEET OS</b><p>Professional mobility across Taiwan, every day.</p></div><div><Link href="/help">Help center</Link><Link href="/account/bookings">My bookings</Link><Link href="/fleet">Our fleet</Link></div><span>© 2026 Fleet OS. Demo experience.</span></footer></div>
 {drawer&&<><button aria-label="Close menu overlay" className="overlay" onClick={()=>setDrawer(false)}/><aside className="drawer" role="dialog" aria-modal="true"><div className="drawer-head"><b>FLEET OS</b><button ref={closeRef} onClick={()=>setDrawer(false)}><X/></button></div><p className="muted">Your Taiwan journey, all in one place.</p>{drawerNav.map(([x,h,I])=><Link onClick={()=>setDrawer(false)} href={h} key={x}><I size={20}/>{x}</Link>)}</aside></>}
 <nav className="mobile-nav">{nav.slice(0,5).map(([label,href,Icon])=><Link href={href} key={label}><Icon/><small>{label.split(' ')[0]}</small></Link>)}</nav></div>}
