'use client';
import Link from 'next/link';import {useRef,useState} from 'react';import {Plane,ShieldCheck,Clock3,CarFront,Play,CloudSun,ArrowRight,Heart,ChevronLeft,ChevronRight,Users,BriefcaseBusiness,Star} from 'lucide-react';import {BookingPanel} from '@/components/booking/BookingPanel';import {formatTwd} from '@/lib/pricing';import {ServiceType} from '@/types';
type HomeService={id:ServiceType;title:string;desc:string;href:string;image:string};type HomeRoute={id:string;from:string;to:string;duration:string;km:number;price:number;image:string};type HomeVehicle={id:string;slug:string;name:string;category:string;image:string;seats:number;luggage:number;basePrice:number};type Hero={title:string;highlightedText:string;subtitle:string;desktopImage:string};
export function HomePage({services,routes,vehicles,hero}:{services:HomeService[];routes:HomeRoute[];vehicles:HomeVehicle[];hero:Hero}){const[video,setVideo]=useState(false);const[favs,setFavs]=useState<string[]>(()=>[]);const[cat,setCat]=useState('All');const fleetRef=useRef<HTMLDivElement>(null);const toggle=(id:string)=>{const n=favs.includes(id)?favs.filter(x=>x!==id):[...favs,id];setFavs(n);localStorage.setItem('fleet-favorites',JSON.stringify(n))};
 return <main><section className="hero" style={{backgroundImage:`url('${hero.desktopImage}')`}}><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow">PREMIUM TAIWAN MOBILITY</span><h1>{hero.title}.<br/><em>{hero.highlightedText}.</em></h1><p>{hero.subtitle}</p><div className="badges"><span><ShieldCheck/>Professional drivers</span><span><CarFront/>Multiple vehicle types</span><span><Clock3/>Instant booking</span></div></div><div className="hero-widgets"><div><Plane/><span><b>Taoyuan Airport (TPE)</b><small>38 min · 34 km to Taipei</small></span></div><div><CloudSun/><span><b>Taipei · 28°C</b><small>Partly cloudy · Air quality good</small></span></div><button onClick={()=>setVideo(true)}><Play/> Watch our journey</button></div></section><div className="home-content"><BookingPanel serviceOptions={services}/>
 <section><div className="section-head"><div><span className="eyebrow">WAYS TO MOVE</span><h2>One platform. Every journey.</h2></div><Link href="/fleet">Explore all services <ArrowRight/></Link></div><div className="service-grid">{services.map((s,i)=><Link href={`${s.href}#book`} className="service-card" key={s.id}><img src={s.image} alt=""/><div><i>0{i+1}</i><h3>{s.title}</h3><p>{s.desc}</p><span>Book now <ArrowRight/></span></div></Link>)}</div></section>
 <section><div className="section-head"><div><span className="eyebrow">CURATED FOR YOU</span><h2>Popular journeys</h2></div><Link href="/destinations">View all <ArrowRight/></Link></div><div className="routes-grid">{routes.map(r=><article className="route-card" key={r.id}><div className="route-image" style={{backgroundImage:`url('${r.image}')`}}><button aria-label="Favorite" onClick={()=>toggle(r.id)} className={favs.includes(r.id)?'liked':''}><Heart fill={favs.includes(r.id)?'currentColor':'none'}/></button></div><div><h3>{r.from} <ArrowRight/> {r.to}</h3><p>{r.duration} · {r.km} km</p><b>From {formatTwd(r.price)}</b></div></article>)}</div></section>
 <section className="fleet-section"><div className="section-head"><div><span className="eyebrow">THE FLEET</span><h2>A better class of travel</h2></div><div className="carousel-buttons"><button onClick={()=>fleetRef.current?.scrollBy({left:-350,behavior:'smooth'})}><ChevronLeft/></button><button onClick={()=>fleetRef.current?.scrollBy({left:350,behavior:'smooth'})}><ChevronRight/></button></div></div><div className="filters">{['All','Sedan','SUV','MPV','Luxury','Minibus','Coach'].map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="fleet-carousel" ref={fleetRef} tabIndex={0}>{vehicles.filter(v=>cat==='All'||v.category===cat).map(v=><Link href={`/fleet/${v.slug}`} className="fleet-card" key={v.id}><img src={v.image} alt={v.name}/><span>{v.category}</span><h3>{v.name}</h3><p><Users/> {v.seats} seats <BriefcaseBusiness/> {v.luggage} bags</p><b>From {formatTwd(v.basePrice)}</b></Link>)}</div></section>
 <section className="trust"><div><b>10,000+</b><span>Professional rides</span></div><div><b>50,000+</b><span>Happy travelers</span></div><div><b>24/7</b><span>Human support</span></div><div><b>100%</b><span>Safety commitment</span></div><div><b><Star fill="currentColor"/>4.8/5</b><span>Verified rating</span></div></section></div>
 {video&&<div className="modal-backdrop" onClick={()=>setVideo(false)}><div className="video-modal" onClick={e=>e.stopPropagation()}><button onClick={()=>setVideo(false)}>×</button><div><Play/><h2>Across Taiwan, together.</h2><p>A cinematic preview of the people, places, and premium vehicles behind every FLEET OS journey.</p></div></div></div>}</main>}
